name: islamicapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.1+8

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^1.2.1
  cloud_firestore: ^5.4.4
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.2
  audioplayers: ^5.2.0
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  intl: ^0.19.0
  geolocator: ^10.1.0
  flutter_compass: ^0.8.0
  url_launcher: ^6.3.2
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

# ⬇⬇⬇ ICI, PAS DANS dev_dependencies
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/default.jpg
    - assets/sounds/
